on:
  push:
    branches: [main, dev]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install NPM Dependencies
      run: npm install
    - name: Run Build
      run: npm run build
    - name: Run Linting
      run: npm run lint
    - name: Run Unit & Integration Tests
      run: npm test
    # - name: Install Playwright Dependencies
    #   run: sudo npx playwright install-deps
    # - name: Run End-to-End Tests
    #   run: npm run test:e2e
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
